version: "3.8"
services:
  db:
    image: mysql
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: togodo
      MYSQL_USER: togodo
      MYSQL_PASSWORD: secret
    networks:
      - togodo-cli-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  togodo-cli-network:
    name: togodo-cli-network
    driver: bridge